# Generated by Django 4.2.2 on 2023-06-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de categoria')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre producto')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('imagen', models.ImageField(default='nn.jpg', upload_to='imagenes/', verbose_name='imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
    ]
